version: "3"
services:
  api:
    image: node:14
    container_name: api-server
    working_dir: /app
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
