# Stage 1: Build the React application
FROM node:14 as build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

EXPOSE 3000

# Copy the entire application
COPY . .


CMD [ "npm","start"]
# Build the React app
#RUN npm run build

# Stage 2: Serve the React application with nginx
#FROM nginx:alpine

# Copy build output from the previous stage
#COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80
#EXPOSE 80

# Default command to run nginx
#CMD ["nginx", "-g", "daemon off;"]
